import type { SafeErrorParams } from '~/types/api'
import { errorI18nKey, normalizeFetchError } from '~/utils/api-error'
export type NoticeTone='info'|'success'|'warning'|'error'|'loading'
export type NoticeMessage={type:'i18n',key:string,params?:SafeErrorParams}|{type:'literal',value:string}
export interface PPNoticeAction{labelKey:string,run:()=>void|Promise<void>}
export interface PPNotice{id:string,tone:NoticeTone,titleKey?:string,message:NoticeMessage,requestId?:string,durationMs?:number|null,dismissible?:boolean,dedupKey?:string,action?:PPNoticeAction}
export interface NoticeOptions extends Partial<Omit<PPNotice,'id'|'tone'|'message'>>{params?:SafeErrorParams}
const D:Record<NoticeTone,number|null>={info:4200,success:4200,warning:6000,error:8000,loading:null};const timers=new Map<string,ReturnType<typeof setTimeout>>()
export function useNotice(){const queue=useState<PPNotice[]>('panel:pp-notice-queue',()=>[]);const{t}=usePanelI18n();const visible=computed(()=>queue.value.slice(0,3));function clear(id:string){const x=timers.get(id);if(x)clearTimeout(x);timers.delete(id)}function dismiss(id:string){clear(id);queue.value=queue.value.filter(x=>x.id!==id)}function schedule(n:PPNotice){clear(n.id);const ms=n.durationMs===undefined?D[n.tone]:n.durationMs;if(ms==null||ms<=0)return;timers.set(n.id,setTimeout(()=>dismiss(n.id),ms))}function add(tone:NoticeTone,message:NoticeMessage,o:NoticeOptions={}){const{params:_params,...rest}=o;const id=globalThis.crypto?.randomUUID?.()??`notice-${Date.now()}-${Math.random().toString(36).slice(2)}`;const n:PPNotice={id,tone,message,dismissible:o.dismissible??tone!=='loading',...rest};if(n.dedupKey){const i=queue.value.findIndex(x=>x.dedupKey===n.dedupKey);if(i>=0){clear(queue.value[i]!.id);queue.value.splice(i,1,n);schedule(n);return id}}queue.value.push(n);while(queue.value.length>20){const x=queue.value.shift();if(x)clear(x.id)}schedule(n);return id}function push(tone:NoticeTone,key:string,o:NoticeOptions={}){return add(tone,{type:'i18n',key,params:o.params},o)}function update(id:string,patch:Partial<PPNotice>){const i=queue.value.findIndex(x=>x.id===id);if(i<0)return;const n={...queue.value[i]!,...patch};queue.value.splice(i,1,n);schedule(n)}const success=(k:string,o?:NoticeOptions)=>push('success',k,o);const info=(k:string,o?:NoticeOptions)=>push('info',k,o);const warning=(k:string,o?:NoticeOptions)=>push('warning',k,o);const error=(k:string,o?:NoticeOptions)=>push('error',k,o);function errorFromApi(err:unknown,o:NoticeOptions={}){const e=normalizeFetchError(err);const key=errorI18nKey(e);const rendered=t(key,e.details.params);return add('error',rendered===key?{type:'i18n',key:'errors.client.UNKNOWN_ERROR'}:{type:'i18n',key,params:e.details.params},{...o,requestId:e.requestId,durationMs:o.durationMs??8000})}async function promise<T>(task:Promise<T>,keys:{loading:string,success:string},o:NoticeOptions={}){const id=push('loading',keys.loading,{...o,durationMs:null,dismissible:false});try{const v=await task;update(id,{tone:'success',message:{type:'i18n',key:keys.success},dismissible:true,durationMs:4200});return v}catch(err){const e=normalizeFetchError(err);const key=errorI18nKey(e);const rendered=t(key,e.details.params);update(id,{tone:'error',message:rendered===key?{type:'i18n',key:'errors.client.UNKNOWN_ERROR'}:{type:'i18n',key,params:e.details.params},requestId:e.requestId,dismissible:true,durationMs:8000});throw err}}function renderMessage(n:PPNotice){return n.message.type==='literal'?n.message.value:t(n.message.key,n.message.params)}return{queue,visible,push,update,success,info,warning,error,errorFromApi,promise,dismiss,renderMessage}}
