/** Compatibility barrel. New admin code imports its domain API from `~/features/<domain>/api`. */
export * from '~/features/permissions/api'
export * from '~/features/groups/api'
export * from '~/features/users/api'
export * from '~/features/rooms/api'
export * from '~/features/server/api'
export * from '~/features/config/api'
export * from '~/features/plugins/api'
export * from '~/features/logs/api'
export * from '~/features/console/api'
export * from '~/features/audit/api'
export * from '~/features/jobs/api'
export * from '~/features/notifications/api'
export * from '~/features/redemption/api'
export * from '~/features/automation/api'
export * from '~/features/site/api'
